
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eihuozrjkodiwbbdrtzn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpaHVvenJqa29kaXdiYmRydHpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NzM0MjYsImV4cCI6MjA2MzE0OTQyNn0.yKshABVgFCQI5RhApw7202v3Q81xwgHnITTPUL2vA4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
